// Copyright (c) 2025 .NET Foundation and Contributors. All rights reserved.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated />
#if !(WINDOWS)
using System.Diagnostics;
using System.Runtime.ExceptionServices;
#if !REACTIVE_SHIM
using ReactiveUI.Primitives.Concurrency;
#endif
using Windows.UI.Core;

#if REACTIVE_SHIM

namespace ReactiveUI.Uno.Reactive;
#else

namespace ReactiveUI.Uno;
#endif

/// <summary>
/// Represents an object that schedules units of work on a <see cref="CoreDispatcher"/>.
/// </summary>
[CLSCompliant(false)]
public sealed class UnoDispatcherScheduler : ISequencer
{
    /// <summary>
    /// Constructs a <see cref="UnoDispatcherScheduler"/> that schedules units of work on the given <see cref="CoreDispatcher"/>.
    /// </summary>
    /// <param name="dispatcher">Dispatcher to schedule work on.</param>
    /// <exception cref="ArgumentNullException"><paramref name="dispatcher"/> is <c>null</c>.</exception>
    public UnoDispatcherScheduler(CoreDispatcher dispatcher)
    {
        Dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));
        Priority = CoreDispatcherPriority.Normal;
    }

    /// <summary>
    /// Constructs a <see cref="UnoDispatcherScheduler"/> that schedules units of work on the given <see cref="CoreDispatcher"/> with the given priority.
    /// </summary>
    /// <param name="dispatcher">Dispatcher to schedule work on.</param>
    /// <param name="priority">Priority for scheduled units of work.</param>
    /// <exception cref="ArgumentNullException"><paramref name="dispatcher"/> is <c>null</c>.</exception>
    public UnoDispatcherScheduler(CoreDispatcher dispatcher, CoreDispatcherPriority priority)
    {
        Dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));
        Priority = priority;
    }

    /// <summary>
    /// Gets the scheduler that schedules work on the <see cref="CoreDispatcher"/> associated with the current Window.
    /// </summary>
    public static UnoDispatcherScheduler Current
    {
        get
        {
            var window = Window.Current;
            if (window == null)
            {
                throw new InvalidOperationException("There is no current window that has been created.");
            }

            return new UnoDispatcherScheduler(window.Dispatcher);
        }
    }

    /// <summary>
    /// Gets the <see cref="CoreDispatcher"/> associated with the <see cref="UnoDispatcherScheduler"/>.
    /// </summary>
    public CoreDispatcher Dispatcher { get; }

    /// <summary>
    /// Gets the priority at which work is scheduled.
    /// </summary>
    public CoreDispatcherPriority Priority { get; }

    /// <inheritdoc/>
    public DateTimeOffset Now => DateTimeOffset.UtcNow;

#if REACTIVE_SHIM
    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, Func<IScheduler, TState, IDisposable> action)
    {
        ArgumentNullException.ThrowIfNull(action);

        var disposable = new SingleAssignmentDisposable();
        _ = Dispatcher.RunAsync(Priority, () =>
        {
            if (!disposable.IsDisposed)
            {
                disposable.Disposable = action(this, state);
            }
        });

        return disposable;
    }

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, TimeSpan dueTime, Func<IScheduler, TState, IDisposable> action)
    {
        ArgumentNullException.ThrowIfNull(action);

        if (dueTime <= TimeSpan.Zero)
        {
            return Schedule(state, action);
        }

        var disposable = new SingleAssignmentDisposable();
        var timer = new DispatcherTimer
        {
            Interval = dueTime
        };

        timer.Tick += OnTick;
        timer.Start();

        return Disposable.Create(() =>
        {
            timer.Stop();
            timer.Tick -= OnTick;
            disposable.Dispose();
        });

        void OnTick(object sender, object args)
        {
            timer.Stop();
            timer.Tick -= OnTick;

            if (!disposable.IsDisposed)
            {
                disposable.Disposable = Schedule(state, action);
            }
        }
    }

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, DateTimeOffset dueTime, Func<IScheduler, TState, IDisposable> action) =>
        Schedule(state, dueTime - Now, action);
#else
    /// <inheritdoc/>
    public long Timestamp => Stopwatch.GetTimestamp();

    /// <inheritdoc/>
    public void Schedule(IWorkItem item)
    {
        ArgumentNullException.ThrowIfNull(item);

        _ = Dispatcher.RunAsync(Priority, () => Execute(item));
    }

    /// <inheritdoc/>
    public void Schedule(IWorkItem item, long dueTimestamp)
    {
        ArgumentNullException.ThrowIfNull(item);

        var timestamp = Timestamp;
        var dueTime = dueTimestamp <= timestamp ? TimeSpan.Zero : Stopwatch.GetElapsedTime(timestamp, dueTimestamp);
        if (dueTime == TimeSpan.Zero)
        {
            Schedule(item);
            return;
        }

        ScheduleSlow(item, Sequencer.Normalize(dueTime));
    }

    /// <summary>
    /// Schedules the specified work item to be executed after the given due time on the dispatcher.
    /// </summary>
    /// <param name="item">The work item to execute.</param>
    /// <param name="dueTime">The time interval to wait before executing the action.</param>
    private static void ScheduleSlow(IWorkItem item, TimeSpan dueTime)
    {
        var timer = new DispatcherTimer();

        timer.Tick += OnTick;
        timer.Interval = dueTime;
        timer.Start();

        void OnTick(object sender, object args)
        {
            timer.Stop();
            timer.Tick -= OnTick;
            Execute(item);
        }
    }
#endif

    /// <summary>
    /// Schedules a periodic piece of work on the dispatcher, using a <see cref="DispatcherTimer"/> object.
    /// </summary>
    /// <typeparam name="TState">The type of the state passed to the scheduled action.</typeparam>
    /// <param name="state">Initial state passed to the action upon the first iteration.</param>
    /// <param name="period">Period for running the work periodically.</param>
    /// <param name="action">Action to be executed, potentially updating the state.</param>
    /// <returns>The disposable object used to cancel the scheduled recurring action (best effort).</returns>
    /// <exception cref="ArgumentNullException"><paramref name="action"/> is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="period"/> is less than <see cref="TimeSpan.Zero"/>.</exception>
    public IDisposable SchedulePeriodic<TState>(TState state, TimeSpan period, Func<TState, TState> action)
    {
        if (period < TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(period));
        }

        if (action == null)
        {
            throw new ArgumentNullException(nameof(action));
        }

        var timer = new DispatcherTimer();

        var state1 = state;

        timer.Tick += (_, _) =>
        {
            state1 = action(state1);
        };

        timer.Interval = period;
        timer.Start();

        return Disposable.Create(() =>
        {
            timer.Stop();
            action = static item => item;
        });
    }

#if !REACTIVE_SHIM
    private static void Execute(IWorkItem item)
    {
        try
        {
            item.Execute();
        }
        catch (Exception ex)
        {
            var timer = new DispatcherTimer
            {
                Interval = TimeSpan.Zero
            };

            timer.Tick += (_, _) =>
            {
                timer.Stop();
                ExceptionDispatchInfo.Capture(ex).Throw();
            };

            timer.Start();
        }
    }
#endif
}
#endif
