// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT License.
// See the LICENSE file in the project root for more information.
// <auto-generated />
#if WINDOWS

using System.Diagnostics;
using Microsoft.UI.Dispatching;
#if !REACTIVE_SHIM
using ReactiveUI.Primitives.Concurrency;
#endif

#if REACTIVE_SHIM

namespace ReactiveUI.Uno.Reactive;
#else

namespace ReactiveUI.Uno;
#endif

/// <summary>
/// Represents an object that schedules units of work on a <see cref="Microsoft.UI.Dispatching.DispatcherQueue"/>.
/// </summary>
public partial class UnoWinUIDispatcherScheduler : ISequencer
{
    /// <summary>
    /// Gets the scheduler that schedules work on the <see cref="Microsoft.UI.Dispatching.DispatcherQueue"/> for the current thread.
    /// </summary>
    public static UnoWinUIDispatcherScheduler Current
    {
        get
        {
            var dispatcher = DispatcherQueue.GetForCurrentThread();
            if (dispatcher == null)
            {
                throw new InvalidOperationException("There is no current dispatcher thread");
            }

            return new UnoWinUIDispatcherScheduler(dispatcher);
        }
    }

    /// <summary>
    /// Constructs a <see cref="UnoWinUIDispatcherScheduler"/> that schedules units of work on the given <see cref="Microsoft.UI.Dispatching.DispatcherQueue"/>.
    /// </summary>
    /// <param name="dispatcherQueue"><see cref="Microsoft.UI.Dispatching.DispatcherQueue"/> to schedule work on.</param>
    /// <exception cref="ArgumentNullException"><paramref name="dispatcherQueue"/> is <c>null</c>.</exception>
    public UnoWinUIDispatcherScheduler(DispatcherQueue dispatcherQueue)
    {
        DispatcherQueue = dispatcherQueue ?? throw new ArgumentNullException(nameof(dispatcherQueue));
        Priority = DispatcherQueuePriority.Normal;
    }

    /// <summary>
    /// Constructs a DispatcherScheduler that schedules units of work on the given <see cref="Microsoft.UI.Dispatching.DispatcherQueue"/> at the given priority.
    /// </summary>
    /// <param name="dispatcherQueue"><see cref="Microsoft.UI.Dispatching.DispatcherQueue"/> to schedule work on.</param>
    /// <param name="priority">Priority at which units of work are scheduled.</param>
    /// <exception cref="ArgumentNullException"><paramref name="dispatcherQueue"/> is <c>null</c>.</exception>
    public UnoWinUIDispatcherScheduler(DispatcherQueue dispatcherQueue, DispatcherQueuePriority priority)
    {
        DispatcherQueue = dispatcherQueue ?? throw new ArgumentNullException(nameof(dispatcherQueue));
        Priority = priority;
    }

    /// <summary>
    /// Gets the <see cref="Microsoft.UI.Dispatching.DispatcherQueue"/> associated with the <see cref="UnoWinUIDispatcherScheduler"/>.
    /// </summary>
    public DispatcherQueue DispatcherQueue { get; }

    /// <summary>
    /// Gets the priority at which work items will be dispatched.
    /// </summary>
    public DispatcherQueuePriority Priority { get; }

    /// <inheritdoc/>
    public DateTimeOffset Now => DateTimeOffset.UtcNow;

#if REACTIVE_SHIM
    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, Func<IScheduler, TState, IDisposable> action)
    {
        ArgumentNullException.ThrowIfNull(action);

        var disposable = new SingleAssignmentDisposable();
        _ = DispatcherQueue.TryEnqueue(Priority, () =>
        {
            if (!disposable.IsDisposed)
            {
                disposable.Disposable = action(this, state);
            }
        });

        return disposable;
    }

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, TimeSpan dueTime, Func<IScheduler, TState, IDisposable> action)
    {
        ArgumentNullException.ThrowIfNull(action);

        if (dueTime <= TimeSpan.Zero)
        {
            return Schedule(state, action);
        }

        var disposable = new SingleAssignmentDisposable();
        var timer = DispatcherQueue.CreateTimer();

        timer.Interval = dueTime;
        timer.IsRepeating = false;
        timer.Tick += OnTick;
        timer.Start();

        return Disposable.Create(() =>
        {
            timer.Stop();
            timer.Tick -= OnTick;
            disposable.Dispose();
        });

        void OnTick(DispatcherQueueTimer sender, object args)
        {
            sender.Stop();
            sender.Tick -= OnTick;

            if (!disposable.IsDisposed)
            {
                disposable.Disposable = Schedule(state, action);
            }
        }
    }

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, DateTimeOffset dueTime, Func<IScheduler, TState, IDisposable> action) =>
        Schedule(state, dueTime - Now, action);
#else
    /// <inheritdoc/>
    public long Timestamp => Stopwatch.GetTimestamp();

    /// <inheritdoc/>
    public void Schedule(IWorkItem item)
    {
        ArgumentNullException.ThrowIfNull(item);

        _ = DispatcherQueue.TryEnqueue(Priority, () => Execute(item));
    }

    /// <inheritdoc/>
    public void Schedule(IWorkItem item, long dueTimestamp)
    {
        ArgumentNullException.ThrowIfNull(item);

        var timestamp = Timestamp;
        var dueTime = dueTimestamp <= timestamp ? TimeSpan.Zero : Stopwatch.GetElapsedTime(timestamp, dueTimestamp);
        if (dueTime == TimeSpan.Zero)
        {
            Schedule(item);
            return;
        }

        ScheduleSlow(item, Sequencer.Normalize(dueTime));
    }

    private void ScheduleSlow(IWorkItem item, TimeSpan dueTime)
    {
        var timer = DispatcherQueue.CreateTimer();

        timer.Interval = dueTime;
        timer.IsRepeating = false;
        timer.Tick += OnTick;
        timer.Start();

        void OnTick(DispatcherQueueTimer sender, object args)
        {
            sender.Stop();
            sender.Tick -= OnTick;
            Execute(item);
        }
    }
#endif

    /// <summary>
    /// Schedules a periodic piece of work on the dispatcherQueue, using a <see cref="Microsoft.UI.Dispatching.DispatcherQueueTimer"/> object.
    /// </summary>
    /// <typeparam name="TState">The type of the state passed to the scheduled action.</typeparam>
    /// <param name="state">Initial state passed to the action upon the first iteration.</param>
    /// <param name="period">Period for running the work periodically.</param>
    /// <param name="action">Action to be executed, potentially updating the state.</param>
    /// <returns>The disposable object used to cancel the scheduled recurring action (best effort).</returns>
    /// <exception cref="ArgumentNullException"><paramref name="action"/> is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="period"/> is less than <see cref="TimeSpan.Zero"/>.</exception>
    public IDisposable SchedulePeriodic<TState>(TState state, TimeSpan period, Func<TState, TState> action)
    {
        if (period < TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(period));
        }

        if (action == null)
        {
            throw new ArgumentNullException(nameof(action));
        }

        var timer = DispatcherQueue.CreateTimer();

        var state1 = state;

        timer.IsRepeating = true;
        timer.Tick += (_, _) =>
        {
            state1 = action(state1);
        };

        timer.Interval = period;
        timer.Start();

        return Disposable.Create(() =>
        {
            timer.Stop();
            action = static item => item;
        });
    }

#if !REACTIVE_SHIM
    private static void Execute(IWorkItem item)
    {
        item.Execute();
    }
#endif
}
#endif
